/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FastEndpointsErrorResponse_errors}
 */
// @ts-ignore
export function createFastEndpointsErrorResponse_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFastEndpointsErrorResponse_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FastEndpointsErrorResponse}
 */
// @ts-ignore
export function createFastEndpointsErrorResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFastEndpointsErrorResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SageWebApiEndpointsAuthLoginPostRequest}
 */
// @ts-ignore
export function createSageWebApiEndpointsAuthLoginPostRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSageWebApiEndpointsAuthLoginPostRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SageWebApiEndpointsAuthLoginPostResponse}
 */
// @ts-ignore
export function createSageWebApiEndpointsAuthLoginPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSageWebApiEndpointsAuthLoginPostResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SageWebApiEndpointsAuthVerifyPostRequest}
 */
// @ts-ignore
export function createSageWebApiEndpointsAuthVerifyPostRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSageWebApiEndpointsAuthVerifyPostRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SageWebApiEndpointsAuthVerifyPostResponse}
 */
// @ts-ignore
export function createSageWebApiEndpointsAuthVerifyPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSageWebApiEndpointsAuthVerifyPostResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SageWebApiEndpointsAuthWhoAmIGetResponse}
 */
// @ts-ignore
export function createSageWebApiEndpointsAuthWhoAmIGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSageWebApiEndpointsAuthWhoAmIGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFastEndpointsErrorResponse(fastEndpointsErrorResponse: Partial<FastEndpointsErrorResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { fastEndpointsErrorResponse.errors = n.getObjectValue<FastEndpointsErrorResponse_errors>(createFastEndpointsErrorResponse_errorsFromDiscriminatorValue); },
        "message": n => { fastEndpointsErrorResponse.messageEscaped = n.getStringValue() ?? "One or more errors occurred!"; },
        "statusCode": n => { fastEndpointsErrorResponse.statusCode = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFastEndpointsErrorResponse_errors(fastEndpointsErrorResponse_errors: Partial<FastEndpointsErrorResponse_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSageWebApiEndpointsAuthLoginPostRequest(sageWebApiEndpointsAuthLoginPostRequest: Partial<SageWebApiEndpointsAuthLoginPostRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { sageWebApiEndpointsAuthLoginPostRequest.email = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSageWebApiEndpointsAuthLoginPostResponse(sageWebApiEndpointsAuthLoginPostResponse: Partial<SageWebApiEndpointsAuthLoginPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { sageWebApiEndpointsAuthLoginPostResponse.email = n.getStringValue(); },
        "prefix": n => { sageWebApiEndpointsAuthLoginPostResponse.prefix = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSageWebApiEndpointsAuthVerifyPostRequest(sageWebApiEndpointsAuthVerifyPostRequest: Partial<SageWebApiEndpointsAuthVerifyPostRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { sageWebApiEndpointsAuthVerifyPostRequest.email = n.getStringValue(); },
        "token": n => { sageWebApiEndpointsAuthVerifyPostRequest.token = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSageWebApiEndpointsAuthVerifyPostResponse(sageWebApiEndpointsAuthVerifyPostResponse: Partial<SageWebApiEndpointsAuthVerifyPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { sageWebApiEndpointsAuthVerifyPostResponse.email = n.getStringValue(); },
        "id": n => { sageWebApiEndpointsAuthVerifyPostResponse.id = n.getStringValue(); },
        "image": n => { sageWebApiEndpointsAuthVerifyPostResponse.image = n.getStringValue(); },
        "name": n => { sageWebApiEndpointsAuthVerifyPostResponse.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSageWebApiEndpointsAuthWhoAmIGetResponse(sageWebApiEndpointsAuthWhoAmIGetResponse: Partial<SageWebApiEndpointsAuthWhoAmIGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { sageWebApiEndpointsAuthWhoAmIGetResponse.email = n.getStringValue(); },
        "id": n => { sageWebApiEndpointsAuthWhoAmIGetResponse.id = n.getStringValue(); },
        "image": n => { sageWebApiEndpointsAuthWhoAmIGetResponse.image = n.getStringValue(); },
        "name": n => { sageWebApiEndpointsAuthWhoAmIGetResponse.name = n.getStringValue(); },
    }
}
export interface FastEndpointsErrorResponse extends ApiError, Parsable {
    /**
     * The errors property
     */
    errors?: FastEndpointsErrorResponse_errors | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The statusCode property
     */
    statusCode?: number | null;
}
export interface FastEndpointsErrorResponse_errors extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface SageWebApiEndpointsAuthLoginPostRequest extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
}
export interface SageWebApiEndpointsAuthLoginPostResponse extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The prefix property
     */
    prefix?: string | null;
}
export interface SageWebApiEndpointsAuthVerifyPostRequest extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The token property
     */
    token?: string | null;
}
export interface SageWebApiEndpointsAuthVerifyPostResponse extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The image property
     */
    image?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface SageWebApiEndpointsAuthWhoAmIGetResponse extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The image property
     */
    image?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFastEndpointsErrorResponse(writer: SerializationWriter, fastEndpointsErrorResponse: Partial<FastEndpointsErrorResponse> | undefined | null = {}) : void {
    if (fastEndpointsErrorResponse) {
        writer.writeObjectValue<FastEndpointsErrorResponse_errors>("errors", fastEndpointsErrorResponse.errors, serializeFastEndpointsErrorResponse_errors);
        writer.writeStringValue("message", fastEndpointsErrorResponse.messageEscaped ?? "One or more errors occurred!");
        writer.writeNumberValue("statusCode", fastEndpointsErrorResponse.statusCode);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFastEndpointsErrorResponse_errors(writer: SerializationWriter, fastEndpointsErrorResponse_errors: Partial<FastEndpointsErrorResponse_errors> | undefined | null = {}) : void {
    if (fastEndpointsErrorResponse_errors) {
        writer.writeAdditionalData(fastEndpointsErrorResponse_errors.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSageWebApiEndpointsAuthLoginPostRequest(writer: SerializationWriter, sageWebApiEndpointsAuthLoginPostRequest: Partial<SageWebApiEndpointsAuthLoginPostRequest> | undefined | null = {}) : void {
    if (sageWebApiEndpointsAuthLoginPostRequest) {
        writer.writeStringValue("email", sageWebApiEndpointsAuthLoginPostRequest.email);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSageWebApiEndpointsAuthLoginPostResponse(writer: SerializationWriter, sageWebApiEndpointsAuthLoginPostResponse: Partial<SageWebApiEndpointsAuthLoginPostResponse> | undefined | null = {}) : void {
    if (sageWebApiEndpointsAuthLoginPostResponse) {
        writer.writeStringValue("email", sageWebApiEndpointsAuthLoginPostResponse.email);
        writer.writeStringValue("prefix", sageWebApiEndpointsAuthLoginPostResponse.prefix);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSageWebApiEndpointsAuthVerifyPostRequest(writer: SerializationWriter, sageWebApiEndpointsAuthVerifyPostRequest: Partial<SageWebApiEndpointsAuthVerifyPostRequest> | undefined | null = {}) : void {
    if (sageWebApiEndpointsAuthVerifyPostRequest) {
        writer.writeStringValue("email", sageWebApiEndpointsAuthVerifyPostRequest.email);
        writer.writeStringValue("token", sageWebApiEndpointsAuthVerifyPostRequest.token);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSageWebApiEndpointsAuthVerifyPostResponse(writer: SerializationWriter, sageWebApiEndpointsAuthVerifyPostResponse: Partial<SageWebApiEndpointsAuthVerifyPostResponse> | undefined | null = {}) : void {
    if (sageWebApiEndpointsAuthVerifyPostResponse) {
        writer.writeStringValue("email", sageWebApiEndpointsAuthVerifyPostResponse.email);
        writer.writeStringValue("id", sageWebApiEndpointsAuthVerifyPostResponse.id);
        writer.writeStringValue("image", sageWebApiEndpointsAuthVerifyPostResponse.image);
        writer.writeStringValue("name", sageWebApiEndpointsAuthVerifyPostResponse.name);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSageWebApiEndpointsAuthWhoAmIGetResponse(writer: SerializationWriter, sageWebApiEndpointsAuthWhoAmIGetResponse: Partial<SageWebApiEndpointsAuthWhoAmIGetResponse> | undefined | null = {}) : void {
    if (sageWebApiEndpointsAuthWhoAmIGetResponse) {
        writer.writeStringValue("email", sageWebApiEndpointsAuthWhoAmIGetResponse.email);
        writer.writeStringValue("id", sageWebApiEndpointsAuthWhoAmIGetResponse.id);
        writer.writeStringValue("image", sageWebApiEndpointsAuthWhoAmIGetResponse.image);
        writer.writeStringValue("name", sageWebApiEndpointsAuthWhoAmIGetResponse.name);
    }
}
/* tslint:enable */
/* eslint-enable */
