/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createSageWebApiEndpointsAuthVerifyPostResponseFromDiscriminatorValue, serializeSageWebApiEndpointsAuthVerifyPostRequest, serializeSageWebApiEndpointsAuthVerifyPostResponse, type FastEndpointsErrorResponse, type SageWebApiEndpointsAuthVerifyPostRequest, type SageWebApiEndpointsAuthVerifyPostResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Auth/Verify
 */
export interface VerifyRequestBuilder extends BaseRequestBuilder<VerifyRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SageWebApiEndpointsAuthVerifyPostResponse>}
     * @throws {FastEndpointsErrorResponse} error when the service returns a 400 status code
     */
     post(body: SageWebApiEndpointsAuthVerifyPostRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SageWebApiEndpointsAuthVerifyPostResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SageWebApiEndpointsAuthVerifyPostRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const VerifyRequestBuilderUriTemplate = "{+baseurl}/Auth/Verify";
/**
 * Metadata for all the requests in the request builder.
 */
export const VerifyRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: VerifyRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSageWebApiEndpointsAuthVerifyPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSageWebApiEndpointsAuthVerifyPostRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
