name: ci

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: 📦 Install dependencies
        working-directory: Sage.WebApp
        run: pnpm install --frozen-lockfile
        
      - name: Test
        shell: pwsh
        run: ./build.ps1 test
